config/routes.rb
AlmReport::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }

  root :to => "search#index"
  get "/search/advanced" => "search#index", advanced: true

  get "/search" => "search#show"
  get "/facets" => "search#facets"
  get "/preview" => "preview#index"

  post "/update-session" => "home#update_session"
  get "/select-all-search-results" => "home#select_all_search_results"
  get "/start-over" => "home#start_over"
  get "/get-work-count" => "home#get_work_count"

  scope "reports" do
    get "generate" => "reports#generate"
    get "metrics/:id" => "reports#metrics", as: :metrics
    get "visualizations/:id" => "reports#visualizations", as: :visualizations
    get "download_data/:id" => "reports#download_data", as: :download
  end

  get "/id" => "id#index"
  post "/id" => "id#save"

  get "/upload" => "id#upload"
  post "/upload" => "id#process_upload"

  get "/about" => "static_pages#about"
  get "/samples" => "static_pages#samples"


  namespace :api do
    resources :reports
  end
end

app/models/search.rb
class Search
  include Cacheable
  include Pageable

  def self.find(query, opts = {})
    pages(query, opts, page: :current_page, rows: :rows, count: :docs) do |query, opts|
      if plos?
        SearchPlos.new(query, opts).run
      elsif crossref?
        SearchCrossref.new(query, opts).run
      elsif dataone?
        SearchDataone.new(query, opts).run
      end
    end
  end

  def self.plos?
    ENV["SEARCH"] == "plos"
  end

  def self.crossref?
    ENV["SEARCH"] == "crossref"
  end

  def self.dataone?
    ENV["SEARCH"] == "dataone"
  end

  def self.find_by_ids(ids)
    cache(ids, expires_in: 1.day) do |ids|
      find({ids: ids})[:docs]
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_filter { journals if Search.plos? }

  def index
    search_params[:advanced] ? advanced : simple
  end

  def show
    @tab = :select_works
    @title = "Add Works"

    session[:params] = search_params
    search = Search.find(search_params)

    @results = search[:docs]
    @total_found = search[:found]
    @metadata = search[:metadata]

    session[:facets] = search[:facets]
    @facets = search[:facets]

    if @cart.items.present?
      @results.each do |result|
        result.checked = true if @cart.items.has_key?(result.id)
      end
    end

    set_paging_vars(search_params[:current_page])
  end

  def facets
    @facets = session[:facets]
    redirect_to(root_path) && return unless @facets

    search_params[:facets].each do |facet|
      @facets.toggle(name: facet[:name], value: facet[:value])
    end

    redirect_to search_path(session[:params].merge(@facets.params))
  end

  private

  def simple
    @tab = :select_works

    render "simple"
  end

  def advanced
    @tab = :select_works
    @title = "Advanced Search"

    render "advanced"
  end

  # PLOS

  def journals
    @journals = Solr::Request.get_journals
  end

  private

  def search_params
    params.permit :commit, :everything, :filters, :author, :author_country, :institution,
      :publication_days_ago, :datepicker1, :datepicker2, :subject,
      :cross_published_journal_name, :financial_disclosure, :filters,
      :queryFieldId, :startDateAsStringId, :endDateAsStringId,
      :unformattedQueryId, :journalOpt, :utf8, facets: [:name, :value]

    params.delete_if do |k, v|
      v == "" || v == [""]
    end
  end
end

app/views/search/_crossref_sample_reports.html.slim
section.sample-reports
  .row
    h2 Explore sample reports
  .row
    .three.columns
      a.sample-reports-block-1 href="/search?filter=funder:100000957"
        = image_tag "home.sample.reports.img1.plos-alm.jpg", :height => '173', :width => '216', :alt => 'Sample Reports Funder'
        div.title
          | Funder:
          br
          | Alzheimer's Association
    .three.columns
      a.sample-reports-block-2 href="/search?filter=publisher-name:Wiley-Blackwell"
        = image_tag "home.sample.reports.img2.plos-alm.jpg", :height => '173', :width => '216', :alt => 'Sample Reports Funder'
        div.title
          | Publisher:
          br
          | Wiley-Blackwell
    .three.columns
      a.sample-reports-block-3 href="/search?filter=category-name:Molecular Biology"
        = image_tag "home.sample.reports.img3.plos-alm.jpg", :height => '173', :width => '216', :alt => 'Sample Reports Funder'
        div.title
          | Subject Area:
          br
          | Molecular Biology
    .three.columns
      a.sample-reports-block-4 href='/search?everything="Michael B. Eisen"'
        = image_tag "home.sample.reports.img4.plos-alm.jpg", :height => '173', :width => '216', :alt => 'Sample Reports Funder'
        div.title
          | Author:
          br
          | Michael B. Eisen

app/views/search/_facets.html.slim
- facets.each do |name, items|
  - selected = items.select { |item, value| value[:selected] == true if value.is_a? Hash }
  p= name.to_s.titlecase
  - if selected.present?
    ul
      - selected.each do |value, properties|
        li
          => check_box_tag "remove_facet", "facet", "yes"
          - if name == 'publication_date'
            strong= link_to "#{value[0..3]} (#{properties[:count]})", facets_path(facets: [{ name: name, value: value}])
          - else
            strong= link_to "#{value} (#{properties[:count]})", facets_path(facets: [{ name: name, value: value}])
  - else
    ul
      - items = items.select{ |value, properties| properties[:count] > 0}
      - items.each_with_index do |(value, properties), i|
        li class=(i > 4 ? "additional" : nil) style=(i > 4 ? "display:none;" : nil)
          - if name == 'publication_date'
            = link_to "#{value[0..3]} (#{properties[:count]})", facets_path(facets: [{ name: name, value: value}])
          - else
            = link_to "#{value} (#{properties[:count]})", facets_path(facets: [{ name: name, value: value}])
      - if items.size > 5
        li.see_all= link_to "See all"

app/views/search/_journals.html.slim
' journals:
- if params.has_key?(:filters)
  span.journals #{params[:filters].map{ |j| @journals[j] }.join(" or ")}
- else
  span.journals All Journals

app/views/search/_plos_sample_reports.html.slim
section.sample-reports
  .row
    h2 Explore sample reports
  .row
    .three.columns
      a.sample-reports-block-1 href="/search?utf8=%E2%9C%93&everything=&author=&author_country=&institution=&publication_days_ago=-1&datepicker1=&datepicker2=&subject=&filters%5B%5D=All+Journals&financial_disclosure=Alzheimer%27s+Association&commit=Search"
        = image_tag "home.sample.reports.img1.plos-alm.jpg", :height => '173', :width => '216', :alt => 'Sample Reports Funder'
        div.title
          | Funder:
          br
          | Alzheimer's Association
    .three.columns
      a.sample-reports-block-2 href="/search?utf8=%E2%9C%93&everything=&author=&author_country=&institution=Harvard+University&publication_days_ago=-1&datepicker1=&datepicker2=&subject=&filters%5B%5D=All+Journals&financial_disclosure=&commit=Search"
        = image_tag "home.sample.reports.img2.plos-alm.jpg", :height => '173', :width => '216', :alt => 'Sample Reports Funder'
        div.title
          | Institution:
          br
          | Harvard University
    .three.columns
      a.sample-reports-block-3 href="/search?utf8=%E2%9C%93&everything=&author=&author_country=&institution=&publication_days_ago=-1&datepicker1=&datepicker2=&subject=Evolutionary+Biology&filters%5B%5D=All+Journals&financial_disclosure=&commit=Search"
        = image_tag "home.sample.reports.img3.plos-alm.jpg", :height => '173', :width => '216', :alt => 'Sample Reports Funder'
        div.title
          | Subject Area:
          br
          | Evolutionary Biology
    .three.columns
      a.sample-reports-block-4 href="/search?utf8=%E2%9C%93&everything=&author=Michael+B.+Eisen&author_country=&institution=&publication_days_ago=-1&datepicker1=&datepicker2=&subject=&filters%5B%5D=All+Journals&financial_disclosure=&commit=Search"
        = image_tag "home.sample.reports.img4.plos-alm.jpg", :height => '173', :width => '216', :alt => 'Sample Reports Funder'
        div.title
          | Author:
          br
          | Michael B. Eisen

app/views/search/_search_result.html.slim
// Work info that we want to send to the server when the checkbox is clicked.
// We include publication_date since that is our default sort order on the
// preview list page (and we don't want to have to re-query solr for it).

div.work-info
  - if r.checked
    input(class="check-save-work" type="checkbox" checked="yes"
      name="" id="" value="#{r.key}")
  - else
    input(class="check-save-work" type="checkbox" name="" id=""
      value="#{r.key}" checked=(@all_checked ? "yes" : false))

  a href="http://doi.org/#{r.id}" target="_blank"
    = r.title
  p.authors
    = r.authors
  p
    = superhumanize(r.type)
    span<> |
    - if r.article_type
      = r.article_type
      span<> |
    = r.published
    - if r.type == "journal-article"
      span<> |
      = r.journal
    - if %w[journal journal-issue journal-article].include?(r.type) && r.publisher
      span<> |
      = r.publisher

app/views/search/_user_reports.html.slim
.section.sample-reports
  .row
    h2 Your previous reports
    - current_user.reports[0...12].in_groups_of(6) do |reports|
        - reports.each do |report|
          .two.columns
            - if report
              a.sample-reports-block-1 href="/reports/metrics/#{report.id}"
                .number= report.id
                .title= report.created_at.to_s(:short)

app/views/search/_work_list.html.slim
= form_tag("/update-session")
  = csrf_meta_tag
  .list
    - @results.each do |result|
      - if Search.plos?
        = render "search/search_result", r: result, all_checked: @all_checked
      - elsif Search.crossref?
        = render "search/search_result", r: result, all_checked: @all_checked

= render "pager", :results_per_page => ENV["PER_PAGE"].to_i

app/views/search/advanced.html.slim
.row
  .eight.columns
    = form_tag search_path, method: :get, class: "advanced-form"

      h2
        ' Construct Your Search
        = link_to "Simple Search", root_path

      .input-holder
        = select_tag "queryFieldId", options_for_select({ \
          "----- Popular -----" => 'divider', \
          "All Fields" => 'everything', \
          "Title" => 'title', \
          "Author" => 'author', \
          "Abstract" => 'abstract', \
          "Subject" => 'subject', \
          "Publication Date" => 'publication_date', \
          "----- Other -----" => 'divider', \
          "Accepted Date" => 'accepted_date', \
          "Work DOI (Digital Object Identifier)" => 'id', \
          "Work Type" => 'article_type', \
          "Author Affiliations" => 'affiliate', \
          "Competing Interest Statement" => 'competing_interest', \
          "Conclusions" => 'conclusions', \
          "Editor" => 'editor', \
          "eNumber" => 'elocation_id', \
          "Figure & Table Captions" => 'figure_table_caption', \
          "Financial Disclosure Statement" => 'financial_disclosure', \
          "Introduction" => 'introduction', \
          "Issue Number" => 'issue', \
          "Materials and Methods" => 'materials_and_methods', \
          "Received Date" => 'received_date', \
          "References" => 'reference', \
          "Results and Discussion" => 'results_and_discussion', \
          "Supporting Information" => 'supporting_information', \
          "Trial Registration" => 'trial_registration', \
          "Volume Number" => 'volume' \
        }, disabled: 'divider'), title: "Search Field"

        #queryTermDivBlockId
          = text_field_tag "queryTermId", nil, placeholder: "Enter search terms", title: "Search Terms"

        #startAndEndDateDivBlockId class="date-input-fields" style="display:none;"
          = text_field_tag 'startDateAsStringId', nil, placeholder: "MM-DD-YYYY"
          span<> to
          = text_field_tag 'endDateAsStringId', nil, placeholder: "MM-DD-YYYY"

      #queryConjunction
        label> Add to your search with:
        => button_tag "and", type: 'button', id: "queryConjunctionAndId",  value: 'AND', title: "AND", class: "button-hover-dark-black small-btn"
        => button_tag "or", type: 'button', id: "queryConjunctionOrId",  value: 'OR', title: "OR", class: "button-hover-dark-black small-btn"
        => button_tag "not", type: 'button', id: "queryConjunctionNotId",  value: 'NOT', title: "NOT", class: "button-hover-dark-black small-btn"


      div
        = text_area_tag 'unformattedQueryId', params["unformattedQueryId"], title: "Query"

      .btnwrap
        = submit_tag "Search", class: "button-hover-dark-black submit-btn", id: "advancedQueryButtonId"
        input type="button" name="clearUnformattedQueryButton" id="clearUnformattedQueryButtonId" value="Clear Query" title="Clear Query" class="reset-btn secondary"

      .input-holder.filter-journals
        ol
          li
            label
              input(id="journalsOpt_all" type="radio" name="journalOpt" value="all" title="Search All Journals"
                checked=("checked" unless params["filters"].present?))
              | Search all journals
          li
            label
              input(id="journalsOpt_slct" type="radio" name="journalOpt" value="some" title="Search Selected Journals"
                checked=("checked" if params["filters"].present?))
              | Only search in the following journals:
          li.options
            fieldset#fsJournalOpt
              ul
                - @journals.each do |key, name|
                  li
                    input(id="filters_#{key}" name="filters[]" value="#{key}" type="checkbox"
                      title="Select #{name}" alt="Select Journal #{name} Check Box"
                      checked=("checked" if params["filters"] && params["filters"].include?(key)))
                      | &nbsp;
                    label for="filters_#{key}" #{name}

  .four.columns
    .aside.aside-container
      h2 Find Specific Works
      a.button href="/id/" By DOI/PMID
      a.button href="/upload" Upload File

      .help-block
        h3 Instructions
        ol
          li Choose a field to search from the picklist.
          li Enter search term(s).
          li Click the AND OR or NOT buttons to add terms to the search box.
          li Repeat steps as necessary.
          li Select journals below, if desired.
          li Click Search to run your query.

        h3 Special Characters
        ul
          li The following characters have special meanings to the query engine: <strong> ! &amp; " ' ^ + - | ( ) [ ] { } \ : </strong>
          li Therefore, all of these characters will be "escaped" by preceding each one with a backslash character
          li The wildcard characters <strong>?</strong> and <strong>*</strong> are <i>not</i> escaped
          li The tilde symbol <strong>~</strong> at the end of a single word term indicates a fuzzy search

        h3 Special Words
        ul
          li
            ' The upper-case words <strong>AND</strong>, <strong>OR</strong>, <strong>NOT</strong>
            ' and <strong>TO</strong> have special meanings to the query engine, so these words
            | will be changed to lower-case when they are used as searchable terms

app/views/search/show.html.slim
.row
  .two.columns
    .facets= render "facets", facets: @facets
  .seven.columns
    h2 Add selected works to your list
    p
      - if @total_found > 0
        => "#{@start_result} - #{@end_result} of #{number_with_delimiter(@total_found, :delimiter => ',')} results for"
      - else
        ' No results found for
      - if params.has_key?(:unformattedQueryId)
        span.keyword= params[:unformattedQueryId]
        ' ;
      - else
        - if !params[:everything].nil? && params[:everything].length > 0
          ' keyword:
          span.keyword= params[:everything]
          ' ;
        - if !params[:author].nil? && params[:author].length > 0
          ' author:
          span.author-name= params[:author]
          ' ;
        - if !params[:author_country].nil? &&params[:author_country].length > 0
          ' author country:
          span.author-country= params[:author_country]
          ' ;
        - if @metadata[:publication_date]
          span
            ' publication date:
            span.publication-date>= @metadata[:publication_date][0].strftime("%m-%d-%Y")
            ' to
            span.publication-date= @metadata[:publication_date][1].strftime("%m-%d-%Y")
            ' ;
      - if Search.plos?
        = render 'journals'
      - if Search.crossref?
        span Due to limited availability of ALM data, search results are limited to items published after Jan 1st 2011.
    - if @total_found > 0
      ul.actions
        li.select-all-works-link
          a href="#" select all
        li.unselect-all-works-link
          a href="#" unselect all
        li.sort
          span> Sort by
          = select_tag( \
            :sort, \
            options_for_select( \
              (Search.plos? ? Solr : SearchCrossref)::SORTS.to_a, \
              params[:sort] \
            ), \
            id: "search_results_sort_order_select" \
          )
    p.select-works-message.invisible
      span#select-works-message-text
      span#select-all-works-message-text
    div#select-all-spinner.ajax_spinner
    - @all_checked = false
    = render "work_list"
  .three.columns
    = render "right_nav", :current_page => :add_works

div#gray-out-screen

div#viz-limit-error-message style="display: none;"
  | Although the ALM report data can contain up to #{ENV["WORK_LIMIT"].to_i} works, the maximum size for visualizations is #{ENV["VIZ_LIMIT"]} works.

div#work-limit-error-message style="display: none;"
  | The maximum report size is #{ENV["WORK_LIMIT"].to_i} works. Go to
  a<> href="/preview-list" Preview List
  | and remove works before adding more to your selection.

div#partial-select-all-error-message style="display: none;"

div#solr-500-error-message style="display: none;"
  | Our search server is not responding.  Please try again in a few minutes.

app/views/search/simple.html.slim
.row
  .eight.columns
    = form_tag(search_path, :method => "get", :class => "home-form")
      h2
        | Search all Works
        - if Search.plos?
          =< link_to "Advanced Search", search_advanced_path
      .input-holder
        = label_tag(:everything, "Keyword")
        = text_field_tag(:everything)
      - if Search.plos?
        .input-holder
          = label_tag(:author, "Author")
          = text_field_tag(:author)
        .input-holder
          = label_tag(:author_country, "Author Country")
          = text_field_tag(:author_country)
        .input-holder
          = label_tag(:institution)
          = text_field_tag(:institution)
        .input-holder
          = label_tag(:publication_days_ago, "Publication Date")
          = select_tag(:publication_days_ago, \
              options_for_select( \
                  [["Last 30 days", 30], \
                  ["Last 365 days", 365], \
                  ["Custom date range", 0]]), \
              class: "styled", include_blank: "All Time" )
          .date-input-fields
            = text_field_tag(:datepicker1, nil, :placeholder => "MM-DD-YYYY")
            span to
            = text_field_tag(:datepicker2, nil, :placeholder => "MM-DD-YYYY")
        .input-holder
          = label_tag(:subject, "Subject Area")
          = text_field_tag(:subject, nil, :class => "subject-autocomplete")
        .input-holder
          = label_tag(:cross_published_journal_name, "Journal")
          = collection_select( \
              "filters", "", @journals, :first, :last, class: "styled", \
              include_blank: "All Journals" \
            )
        .input-holder
          = label_tag(:financial_disclosure, "Funder Name or Funding Number")
          = text_field_tag(:financial_disclosure)
      .input-holder
        => submit_tag "Search"
        input type="reset" value="Clear All" class="secondary"
  .four.columns
    .aside.aside-container
      h2 Find Specific Works
      a.button href="/id/" By DOI/PMID
      a.button href="/upload" Upload File

= works_list

- if current_user && current_user.reports.present?
  = render "user_reports"

- if Search.plos?
  = render "plos_sample_reports"
- elsif Search.crossref?
  = render "crossref_sample_reports"