config/routes.rb
AlmReport::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }

  root :to => "search#index"
  get "/search/advanced" => "search#index", advanced: true

  get "/search" => "search#show"
  get "/facets" => "search#facets"
  get "/preview" => "preview#index"

  post "/update-session" => "home#update_session"
  get "/select-all-search-results" => "home#select_all_search_results"
  get "/start-over" => "home#start_over"
  get "/get-work-count" => "home#get_work_count"

  scope "reports" do
    get "generate" => "reports#generate"
    get "metrics/:id" => "reports#metrics", as: :metrics
    get "visualizations/:id" => "reports#visualizations", as: :visualizations
    get "download_data/:id" => "reports#download_data", as: :download
  end

  get "/id" => "id#index"
  post "/id" => "id#save"

  get "/upload" => "id#upload"
  post "/upload" => "id#process_upload"

  get "/about" => "static_pages#about"
  get "/samples" => "static_pages#samples"


  namespace :api do
    resources :reports
  end
end

app/models/report.rb
require 'csv'

class Report < ActiveRecord::Base
  has_and_belongs_to_many :users

  # TODO: figure out what we want the default sort order to be.
  # doi is likely not a good solution.
  has_many :report_dois, -> { order(:sort_order) }

  default_scope { order('created_at desc') }

  # Creates a child ReportDoi object for each DOI passed in in the input array.
  # Sort order is determined by the position in the array.  This object must have
  # already been saved to the DB before this method is called.
  def add_all_dois(dois)
    report_dois = dois.map.with_index do |doi, index|
      {
        doi: doi,
        sort_order: index
      }
    end
    self.report_dois.create(report_dois)
    # Since reports can have many DOIs, for performance we do a batch insert.
    # Active Record won't do this on its own.
    # TEMP DISABLE, PRETTY BAD.
    # sql = "INSERT report_dois(doi, report_id, sort_order, created_at, updated_at) VALUES "
    # dois.each_with_index {|doi, i| sql << "('#{doi}', #{self.id}, #{i}, NOW(), NOW()), "}
    # sql[-2] = ";"
    # self.connection.execute(sql)
  end

  # Sets the @sorted_report_dates field.
  # Precondition: load_works_from_solr has already been called.
  def sort_report_dates
    if @sorted_report_dates.nil?
      @sorted_report_dates = report_dois.collect{|report_doi| report_doi.solr.publication_date}
      @sorted_report_dates.sort!
    end
  end
  private :sort_report_dates


  # Returns the earliest publication date of any work in this report.
  # Precondition: load_works_from_solr has already been called.
  def get_earliest_report_date
    sort_report_dates
    @sorted_report_dates[0]
  end


  # Returns the latest publication date of any work in this report.
  # Precondition: load_works_from_solr has already been called.
  def get_latest_report_date
    sort_report_dates
    @sorted_report_dates[-1]
  end

  def as_json(options = {})
    alm = Alm.get_v5(report_dois.map(&:doi))

    # Ember-friendly JSON formatting
    alm["id"] = id
    alm["items"] = alm.delete("data").map do |result|
      result.update({"id" => result["doi"]})
    end

    search_results = Search.find_by_ids(alm["items"].map{ |i| i["id"] })

    alm["items"].map! do |result|
      s = search_results.find{|s| s.id == result["id"] }
      result["affiliations"] = s.affiliations
      result["journal"] = s.journal
      result["subjects"] = s.subjects.map{|k| k.gsub(/\A\/|\/\Z/, '').split(/\//)}
      result
    end

    { report: alm }
  end

  def to_csv(options = {})
    field = options[:field]

    if (field.nil?)
      alm = Alm.get_data_for_works(report_dois)

      data = report_dois.map do |report_doi|
        report_doi.solr = SearchResult.from_cache(report_doi.doi)
        report_doi.alm = alm[report_doi.doi]
      end

      CSV.generate({ :force_quotes => true }) do | csv |
        title_row = [
            "DOI", "PMID", "Publication Date", "Title", "Authors", "Author Affiliations",
            ]
        title_row += Alm::ALM_METRICS.values
        title_row += [
            "Journal", "Work Type", "Funding Statement", "Subject Areas", "Submission Date",
            "Acceptance Date", "Editors", "Work URL",
            ]
        csv << title_row

        report_dois.each do |report_doi|
          # If the work was unpublished (rare), skip it.
          row = report_doi.to_csv
          csv << row if row
        end
      end
    elsif (field == "doi")
      CSV.generate({ :force_quotes => true}) do | csv |
        csv << ["DOI"]

        report_dois.each do | report_doi |
          csv << [report_doi.doi]
        end
      end
    end
  end

  def has_alm?
    report_dois.index{|r| r.alm.present? }.present?
  end
end

app/controllers/api/reports_controller.rb
class Api::ReportsController < ApplicationController
  respond_to :json

  # API
  def show
    @report = Report.find(params[:id])
    render json: @report
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  # Creates a new report based on the DOIs stored in the session,
  # and redirects to display it.
  def generate
    dois = @cart.items.keys
    # start again if we find no dois
    if dois.blank?
      return redirect_to(search_advanced_path,
                         unformattedQueryId: params[:unformattedQueryId],
                         filters: params[:filters])
    end

    @report = Report.new
    if !@report.save
      raise "Error saving report"
    end

    # associate this report with the current_user
    @report.users << current_user if current_user

    @report.add_all_dois(dois)
    if @report.save
      redirect_to :action => "metrics", :id => @report.id
    else
      # TODO
    end
  end

  # Loads a report based on the report_id, and sets some other common variables
  # used by the reports pages.
  def load_report(id)
    @tab = :view_report
    @report = Report.find(id)

    # Save the report DOIs in the session (overwriting whatever might already be there).
    @cart.clear
    @report.report_dois.each do |report_doi|
      @cart[report_doi.doi] = report_doi.sort_order
    end
  end

  def metrics
    load_report(params[:id])
    @report_sub_tab = :metrics
    @title = "Report Metrics"

    paging_logic = lambda {
      @total_found = @report.report_dois.length
      set_paging_vars(params[:current_page], ENV["METRICS_PER_PAGE"].to_i)

      # Create a new array for display that is only the works on the current page,
      # to limit what we have to load from solr and ALM.
      @dois = @report.report_dois[(@start_result) - 1..(@end_result - 1)]
      alm_data = Alm.get_data_for_works(@dois)
      solr_data = Cart.new(@dois.map(&:doi))
      [solr_data, alm_data]
    }

    @show_metrics_data = true
    if @report.report_dois.length > 0
      @solr_data, @alm_data = paging_logic.call()
      i = @start_result
      dois_to_delete = manage_report_data(@dois, i)
      if (!dois_to_delete.empty?)
        purge_bad_dois(dois_to_delete)

        # We need to re-do paging logic since the number of works has changed.
        @solr_data, @alm_data = paging_logic.call()
        i = @start_result
        manage_report_data(@dois, i)
      end
    else
      @show_metrics_data = false
    end
  end

  # Permanently removes the given DOIs from a report.
  def purge_bad_dois(dois_to_delete)
    logger.warn("Nonexistent DOIs detected; will delete from report: #{@report.id}: #{dois_to_delete.inspect}")

    # delete the bad dois from the report
    ReportDoi.destroy_all(:id => dois_to_delete)
    @report.reload
  end

  def visualizations
    @report_sub_tab = :visualizations
    @title = "Report Visualizations"

    load_report(params[:id])

    if @report.report_dois.length > ENV["VIZ_LIMIT"].to_i
      return flash[:alert] = "Visualizations not enabled for more than " \
        "#{ENV["VIZ_LIMIT"].to_i} reports"
    end
  end

  def manage_report_data(report_dois, display_start_index = 1)

    i = display_start_index
    dois_to_delete = []

    report_dois.each do |doi|
      solr = @solr_data[doi.doi]

      if solr.nil?
        dois_to_delete << doi.id
      else
        doi.solr = solr

        # only try to retrieve the alm data if the work exists in solr
        alm = @alm_data[doi.doi]
        if alm.nil?
          # if there isn't alm data for an work that exists in solr
          # alm had an error for that work or
          # the work is too new to have any alm data
          # either way, display an error message
        else
          doi.alm = alm
        end
      end


      # Set the display index as a property for rendering.
      doi.display_index = i
      i += 1
    end

    return dois_to_delete

  end

  # handles download data links
  def download_data
    load_report(params[:id])
    options = {}
    if (params[:field])
      options[:field] = params[:field]
    end

    filename = (params[:field] == "doi") ? "doilist.csv" : "almreport.csv"

    respond_to do | format |
      format.csv { send_data @report.to_csv(options), :filename => filename }
    end
  end

  private

  def prepare_visualization_data
    @solr_data = Hash[@report.report_dois.map do |report_doi|
      [report_doi.doi, SearchResult.from_cache(report_doi.doi)]
    end]

    dois_to_delete = manage_report_data(@report.report_dois)

    if dois_to_delete.present?
      purge_bad_dois(dois_to_delete)
      # TODO fix sort order
      manage_report_data(@report.report_dois)
    end

    if @report.has_alm?
      @draw_viz = true
    else
      @draw_viz = false
      return
    end
  end

  def single_document_visualizations
    @alm_data = Alm.get_data_for_one_work(@report.report_dois)
    prepare_visualization_data

    #render single work report
    @work_usage_data = ChartData.
      generate_data_for_usage_chart(@report)

    @work_citation_data = ChartData.
      generate_data_for_citation_chart(@report)

    social_scatter_data = ChartData.
      generate_data_for_social_data_chart(@report)
    @social_scatter_header = social_scatter_data[:column_header]
    @social_scatter = social_scatter_data[:data]

    mendeley_reader_data = ChartData.
      generate_data_for_mendeley_reader_chart(@report)
    @reader_data = mendeley_reader_data[:reader_loc_data]
    @reader_total = mendeley_reader_data[:reader_total]
    render "single_document_visualizations"
  end

  def multiple_documents_visualizations
    @alm_data = Alm.get_data_for_works(@report.report_dois)
    prepare_visualization_data

    # for when a report contains many works but very small portion of the
    # works have alm data (without it viz page will look very weird)

    min_data_points = (ENV["MIN_DATA_POINTS"] || 2).to_i

    if @solr_data.length >= min_data_points
      bubble_data = ChartData.bubble_charts(@report)
      @work_usage_citations_age_data = bubble_data[:citation_data]
      @work_usage_mendeley_age_data = bubble_data[:mendeley_data]

      @work_usage_citation_subject_area_data = ChartData.
        subject_area_chart(@report)

      loc_data = ChartData.
        generate_data_for_works_by_location_chart(@report)

      @total_authors_data = loc_data[:total_authors_data]
      @work_locations_data = loc_data[:locations_data]
    else
      @draw_viz = false
    end
    render "multiple_documents_visualizations"
  end

end

app/views/reports/_alm_stat.html.erb
<%#
Partial that renders a single table row on the report-metrics page.
If the data is nil or zero, the row won't be shown.
This partial accepts the following parameters:

  value: the value to render
  label: label to go along with the value
  href: if defined, label will be rendered as a link pointing at this URL

If the above two parameters are undefined, data will be rendered from these
parameters:

  data: ALM data structure returned from Alm
  stat: key into the data dict specifying the value
%>
<%
  value ||= data[stat]
  label ||= Alm::ALM_METRICS[stat]
%>
<tr class="<%= 'metric-without-data' if !(!value.nil? && value > 0) %>">
  <%
    show_link = !(defined?(href)).nil?
    td_class = "list-names"
    if show_link
      td_class += " nona-link"
    end
  %>
  <td class="<%= td_class %>" <%= show_link ? "data-href=#{href}" : "" %>>
    <%= label %>
  </td>
  <td class="metrics-list-value"><%= number_with_delimiter(value, :delimiter => ',') %></td>
</tr>

app/views/reports/_report_share.html.erb
<div class="report-share-block">
  <span class="share-button">Share</span>
  <div class="share-box">
    <a href="https://plus.google.com/share?url=<%=u request.url %>"
        target="_blank" title="Share on Google+"><span class="google-plus-logo"></span><span class="google-plus-text">Google+</span></a>
    <a href="http://www.facebook.com/share.php?u=<%=u request.url %>&amp;t=PLOS%20ALM%20Report"
        target="_blank" title="Share on Facebook"><span class="facebook-logo"></span><span class="facebook-text">Facebook</span></a>
    <a href="http://twitter.com/intent/tweet?text=%23PLOS%20ALM%20Report%3A%20<%=u request.url %>"
        target="_blank" title="Share on Twitter"><span class="twitter-logo"></span><span class="twitter-text">Twitter</span></a>
    <a href="mailto:?to=&subject=PLOS%20ALM%20Report&body=<%=u request.url %>"><span class="email-logo"></span><span class="email-text">Email</span></a>
  </div>
</div>

app/views/reports/_reports_nav.html.slim
nav#report
  = link_to "Metrics Data", {:controller => "reports",  :action => "metrics", :id => @report }, class: ["metrics-icon", (@report_sub_tab == :metrics ? "metrics-icon-active" : nil)]

  - if @report.report_dois.length > ENV["VIZ_LIMIT"].to_i
    .inactive-viz-holder
      span.inactive-viz-link.chart-view Visualizations
      span.inactive-viz-msg The limit for visualizations is #{ENV["VIZ_LIMIT"]} works.

  - else
    = link_to "Visualizations", visualizations_path(@report), class: ["chart-view", (@report_sub_tab == :visualizations ? "chart-view-active" : nil)]

  = render "report_share"

  span.download-visuals
    = link_to "Edit List", preview_path, class: "edit-list"
    a href="/start-over" class="start-over" Start Over

app/views/reports/metrics.html.slim
= render "reports_nav"

.row
  .eight.columns
    .metrics-left-content
      - if @show_metrics_data
        p.metrics-work-count
          | #{@start_result} - #{@end_result} of #{@total_found} works

        - @dois.each do |doi|
          .metrics-list
            h2
              span= doi.display_index
              a href="http://dx.doi.org/#{doi.doi}"
                = doi.solr.title
            - if doi.solr.authors
              p.metrics-para
                = doi.solr.authors
            p.metrics-description
              | Research Work
              span.vertical-separator |
              = doi.solr.published
              span.vertical-separator |
              = doi.solr.journal
              span.vertical-separator |
              a href="http://dx.doi.org/#{doi.doi}"
                = doi.doi

            - if doi.alm.blank?
              .metrics-no-data-para This work data isn't available. Please check back later.
            - else
              p
                a.show-all-alms-link
                  | Show all ALMs
                  span.arrow-down
              .metrics-table-content
                .metric-row-content
                  table.metrics-table class=("metric-without-data" if !doi.alm[:viewed_data_present])
                    caption Viewed
                    = render "alm_stat", :data => doi.alm, :stat => :plos_html
                    = render "alm_stat", :data => doi.alm, :stat => :plos_pdf
                    = render "alm_stat", :data => doi.alm, :stat => :plos_xml
                    = render "alm_stat", :data => doi.alm, :stat => :pmc_views
                    = render "alm_stat", :data => doi.alm, :stat => :pmc_pdf
                    = render "alm_stat", :value => doi.alm[:total_usage], :label => "Total usage"

                  table.metrics-table class=("metric-without-data" if !doi.alm[:saved_data_present])
                    caption Saved
                    = render "alm_stat", :data => doi.alm, :stat => :citeulike
                    = render "alm_stat", :data => doi.alm, :stat => :mendeley
                    = render "alm_stat", :data => doi.alm, :stat => :figshare

                .metric-row-content
                  table.metrics-table class=("metric-without-data" if !doi.alm[:discussed_data_present])
                    caption Discussed
                    = render "alm_stat", :data => doi.alm, :stat => :nature
                    = render "alm_stat", :data => doi.alm, :stat => :researchblogging
                    = render "alm_stat", :data => doi.alm, :stat => :scienceseeker
                    = render "alm_stat", :data => doi.alm, :stat => :facebook
                    = render "alm_stat", :data => doi.alm, :stat => :twitter
                    = render "alm_stat", :data => doi.alm, :stat => :wikipedia
                    = render "alm_stat", :data => doi.alm, :stat => :reddit
                    = render "alm_stat", :data => doi.alm, :stat => :wordpress

                  table.metrics-table class=("metric-without-data" if !doi.alm[:cited_data_present])
                    caption Cited
                    = render "alm_stat", :data => doi.alm, :stat => :pubmed
                    = render "alm_stat", :data => doi.alm, :stat => :crossref
                    = render "alm_stat", :data => doi.alm, :stat => :scopus
                    = render "alm_stat", :data => doi.alm, :stat => :datacite
                    = render "alm_stat", :data => doi.alm, :stat => :pmceurope
                    = render "alm_stat", :data => doi.alm, :stat => :pmceuropedata
                    = render "alm_stat", :data => doi.alm, :stat => :wos

                .metric-row-content
                  table.metrics-table class=("metric-without-data" if !doi.alm[:recommended_data_present])
                    caption Recommended
                    = render "alm_stat", :data => doi.alm, :stat => :f1000
      - if @show_metrics_data
        = render "pager", :results_per_page => 5
  .four.columns
    .report-downloads
      h2 Downloads
      ul
        li
          = link_to({:controller => "reports", :action => "download_data", :id => @report, :format => :csv},
            :html_options => {:id => "metrics-download-link"})
            span.csv
            span.file-name Metrics Data
            span.arrow

        li
          = link_to({:controller => "reports", :action => "download_data", :id => @report, :format => :csv, :field => "doi"})
            span.csv
            span.file-name Your List of Work DOIs
            span.arrow

app/views/reports/multiple_documents_visualizations.html.slim
.content.wrapper
  = render "reports_nav"

  .visualizations-container
    - if @draw_viz
      - if @work_usage_citations_age_data.present?
        .visualizations-list
          .reports-header-div
            span.list-numbers 1
            h2 Work Usage and Citations as a function of Age
          #citations
          p.info
            ' Total usage includes page views and downloads from PLOS and PMC.
            | Bubble size correlates with Scopus citations and bubble color with the PLOS journal.
          p
            ' SOURCE: #{@report.report_dois.length} published works from
            ' #{@report.get_earliest_report_date.strftime("%B %d, %Y")}
            | to #{@report.get_latest_report_date.strftime("%B %d, %Y")}

      - if @work_usage_mendeley_age_data.present?
        .visualizations-list
          .reports-header-div
            span.list-numbers 2
            h2 Work Usage and Bookmarks as a Function of Time
          #saved
            p.info
              Total usage includes page views and downloads from PLOS and PMC.
              Bubble size correlates with bookmarks and bubble color with the PLOS journal.
            p
              ' SOURCE: #{@report.report_dois.length} published works from
              ' #{@report.get_earliest_report_date.strftime("%B %d, %Y")}
              | to #{@report.get_latest_report_date.strftime("%B %d, %Y")}

      - if @work_usage_citation_subject_area_data.present?
        .visualizations-list
          .reports-header-div
            span.list-numbers 3
            h2 Work Usage by Subject Area
          #work_subject_div
            p.info
              Rectangle size correlates with the number of works associated with the subject area and the color intensity with total usage.
            p
              ' SOURCE: #{@report.report_dois.length} published works from
              ' #{@report.get_earliest_report_date.strftime("%B %d, %Y")}
              | to #{@report.get_latest_report_date.strftime("%B %d, %Y")}

      - if @work_locations_data.present?
        .visualizations-list
          .reports-header-div
            span.list-numbers 4
            h2 Research Works by Location
          #work_location_div
            p.info
              Geolocation of #{@total_authors_data} authors for #{@report.report_dois.length} works.
              Bubble size and color correlates with the number of authors in that location.
            p
              ' SOURCE: #{@report.report_dois.length} published works from
              ' #{@report.get_earliest_report_date.strftime("%B %d, %Y")}
              | to #{@report.get_latest_report_date.strftime("%B %d, %Y")}


  .report-downloads
    h2 Print
    ul
      li
        a#download_viz
          span.png
          span.file-name Visualizations
          span.arrow

    = render "report_share"

- content_for :javascript do
  = javascript_include_tag "multiple_documents_visualizations"
  = javascript_include_tag "charts"

app/views/reports/single_document_visualizations.html.slim
div.content.wrapper.cf
  = render "reports_nav"

  - graph_number = 0

  div.visualizations-container
    - if @work_usage_data.present?
      - graph_number = graph_number + 1
      div.visualizations-list
        div.reports-header-div
          span.list-numbers= graph_number
          h2 Work Usage as a function of Age

        #work_usage_div
        p.info Total usage includes page views and downloads from PLOS and PMC.

    - if !@work_citation_data.empty?
      - graph_number = graph_number + 1
      div.visualizations-list
        div.reports-header-div
          span.list-numbers= graph_number
          h2 Work Citations as a function of Age
        #work_citation_div
        p.info Cumulative citations from each of the citation indices.

    - if !@social_scatter.empty?
      - graph_number = graph_number + 1
      div.visualizations-list
        div.reports-header-div
          span.list-numbers= graph_number
          h2 Discussion Activity as a function of Age
        #social_scatter_div
        p.info Activity across blogs, news media, social media, and other online content sources. Those with no activity are not displayed.

    - if @reader_total > 0
      - graph_number = graph_number + 1
      div.visualizations-list
        div.reports-header-div
          span.list-numbers= graph_number
          h2 Mendeley Bookmarks by Location
        #work_mendeley_readers_div
        p.info Geolocation of #{@reader_total} individuals who have saved the work in Mendeley.

    - if graph_number == 0
      div.visualizations-list
        .metrics-no-data-para There isn't enough data to show these visualizations.

  div.report-downloads
    h2 Print
    ul
      li
        a#download_viz
          span.png
          span.file-name Visualizations
          span.arrow

    = render "report_share"

javascript:
  function haveDataToDrawViz() {
    return #{{ @draw_viz }};

  }

  function drawVizForOne() {
    return true;
  }

  function getWorkUsageAge() {
    return #{{ @work_usage_data }};
  }

  function getWorkCitationAge() {
    return #{{ @work_citation_data }};
  }

  function getWorkSocialScatterHeader() {
    return #{{ @social_scatter_header.to_json }};
  }
  function getWorkSocialScatter() {
    return #{{ @social_scatter.to_json }};
  }

  function getWorkMendeley() {
   return  #{{ @reader_data }};
  }

= javascript_include_tag "charts"

app/views/reports/visualizations.html.slim
.container.visualizations
  = render "reports_nav"
  .row
    .twelve.columns
      div.report-downloads
        ul
          li
            a#download_viz
              span.png
              span.file-name Print Visualizations
              span.arrow

      #alm-report

      script type="text/x-handlebars"
        | {{outlet}}

- content_for :javascript do
  = javascript_include_tag "alm_report"